global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: 'object-registry'
    static_configs:
      - targets: ['object-registry:8000']
  - job_name: 'query-service'
    static_configs:
      - targets: ['query-service:8060']
  - job_name: 'planning-control'
    static_configs:
      - targets: ['planning-control:8110']
  - job_name: 'governance-control'
    static_configs:
      - targets: ['governance-control:8120']
