apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: cognimesh-dev
commonLabels:
  environment: development
patches:
  # Enable dev auth for development testing on query-service
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/2/value
        value: "true"
    target:
      kind: Deployment
      name: query-service
